services:
  api:
    # Update the image name to match your GitHub Container Registry
    # Format: ghcr.io/<your-github-username>/kwink-soevai-api:latest
    image: ${LIBRECHAT_IMAGE:-ghcr.io/gradient-ds/soevai-api:latest}
    container_name: librechat_api
    ports:
      - 3080:3080
    depends_on:
      - mongodb
      - rag_api
    restart: always
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
      SOEVAI_ROOT: /app
      CONFIG_PATH: /app/librechat.soev.ai.yaml
      BASE_CONFIG_PATH: /app/soev.ai.yaml
      HOST: 0.0.0.0
      PORT: 3080
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      CREDS_KEY: ${CREDS_KEY}
      CREDS_IV: ${CREDS_IV}
      MONGO_URI: mongodb://mongodb:27017/LibreChat
      MEILI_HOST: http://meilisearch:7700
      RAG_PORT: ${RAG_PORT:-8000}
      RAG_API_URL: http://rag_api:${RAG_PORT:-8000}
      DOMAIN_CLIENT: ${DOMAIN_CLIENT:-https://gradient-testing.nl}
      DOMAIN_SERVER: ${DOMAIN_SERVER:-https://gradient-testing.nl}
      TRUST_PROXY: "1"
      TRUST_REVERSE_PROXY: true
      APP_TITLE: ${APP_TITLE:-kwink.soev.ai}
      
      # Web Search Configuration (External VM)
      # Set these in .env file with the IP/hostname of the scraper VM
      SEARXNG_INSTANCE_URL: ${SEARXNG_INSTANCE_URL:-http://10.0.0.2:8080}
      SEARXNG_API_KEY: ${SEARXNG_API_KEY:-not-needed}
      FIRECRAWL_API_URL: ${FIRECRAWL_API_URL:-http://10.0.0.2:3002}
      FIRECRAWL_API_KEY: ${FIRECRAWL_API_KEY:-default-local-key}
      FIRECRAWL_VERSION: ${FIRECRAWL_VERSION:-v1}
      JINA_API_URL: ${JINA_API_URL:-http://10.0.0.2:8001/v1}
      JINA_API_KEY: ${JINA_API_KEY:-local-proxy-key}
      
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      ALLOW_REGISTRATION: ${ALLOW_REGISTRATION:-false}
      ALLOW_UNVERIFIED_EMAIL_LOGIN: ${ALLOW_UNVERIFIED_EMAIL_LOGIN:-false}
      ALLOW_EMAIL_LOGIN: ${ALLOW_EMAIL_LOGIN:-true}
      CUSTOM_FOOTER: soev.ai - Soevereine AI voor Nederland | Controleer belangrijke informatie, AI kan soms fouten maken.
      CHECK_BALANCE: true
      START_BALANCE: 2000000
      ALLOW_SHARED_LINKS: false
      
      # Social Login Configuration
      ALLOW_SOCIAL_LOGIN: ${ALLOW_SOCIAL_LOGIN:-true}
      OPENID_CLIENT_ID: ${OPENID_CLIENT_ID}
      OPENID_CLIENT_SECRET: ${OPENID_CLIENT_SECRET}
      OPENID_ISSUER: ${OPENID_ISSUER}
      OPENID_SESSION_SECRET: ${OPENID_SESSION_SECRET}
      OPENID_CALLBACK_URL: ${OPENID_CALLBACK_URL}
      OPENID_SCOPE: ${OPENID_SCOPE:-openid profile email}
      OPENID_BUTTON_LABEL: ${OPENID_BUTTON_LABEL:-Login met Microsoft}
      OPENID_REQUIRED_ROLE_TOKEN_KIND: ${OPENID_REQUIRED_ROLE_TOKEN_KIND:-id}
      
      # UbiOps Configuration
      UBIOPS_KEY: ${UBIOPS_KEY}
      NEBUL_API_KEY: ${NEBUL_API_KEY}

      ENDPOINTS: ${ENDPOINTS}
    volumes:
      - ./soev.ai.yaml:/app/soev.ai.yaml:ro
      - ./librechat.soev.ai.yaml:/app/librechat.soev.ai.yaml:rw
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs

  client:
    image: nginx:1.27.0-alpine
    container_name: nginx-soevai
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
      - grafana
      - prometheus
      - alertmanager
      - metrics
    restart: always
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - /srv/soevai/certbot-www:/var/www/certbot
      - /srv/soevai/letsencrypt:/etc/letsencrypt
  mongodb:
    container_name: chat-mongodb
    # ports:  # Uncomment this to access mongodb from outside docker, not safe in deployment
    #   - 27018:27017
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    command: ["mongod", "--bind_ip_all", "--noauth"]

  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.12.3
    restart: always
    # ports: # Uncomment this to access meilisearch from outside docker
    #   - 7700:7700 # if exposing these ports, make sure your master key is not the default value
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - ./meili_data_v1.12:/meili_data
  vectordb:
    image: pgvector/pgvector:0.8.0-pg15-trixie
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    volumes:
      - pgdata2:/var/lib/postgresql/data


  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev:latest
    container_name: dev-rag-api
    restart: unless-stopped
    depends_on:
      - vectordb
    environment:
      DB_HOST: vectordb
      RAG_PORT: 8000
      OPENAI_API_KEY: ${UBIOPS_RAG}
      OPENAI_BASE_URL: ${RAG_OPENAI_BASE_URL}
      EMBEDDINGS_MODEL: ${RAG_EMBEDDINGS_MODEL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      RAG_CHECK_EMBEDDING_CTX_LENGTH: false

  certbot:
    image: certbot/certbot:latest
    container_name: certbot-soevai
    volumes:
      - /srv/soevai/letsencrypt:/etc/letsencrypt
      - /srv/soevai/certbot-www:/var/www/certbot
      - /srv/soevai/letsencrypt-log:/var/log/letsencrypt
    entrypoint: >-
      /bin/sh -c '
        trap exit TERM;
        while :; do
          certbot renew --quiet || true;
          sleep 12h;
        done'
    depends_on:
      - client
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  # MONITORING STACK
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-soevai
    restart: always
    volumes:
      - ./monitoring/prometheus/prometheus-prod.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.external-url=https://${FQDN:-localhost}/prometheus'
      - '--web.route-prefix=/prometheus'
    environment:
      ENVIRONMENT: 'production'
    depends_on:
      - metrics

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager-soevai
    restart: always
    volumes:
      - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    environment:
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL:-}
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        if [ -n "$$SLACK_WEBHOOK_URL" ]; then
          echo "$$SLACK_WEBHOOK_URL" > /tmp/slack_webhook
        else
          echo "https://hooks.slack.com/services/placeholder" > /tmp/slack_webhook
        fi
        exec /bin/alertmanager \
          --config.file=/etc/alertmanager/alertmanager.yml \
          --storage.path=/alertmanager \
          --web.external-url=https://${FQDN:-localhost}/alertmanager \
          --web.route-prefix=/alertmanager \
          --cluster.listen-address= \
          --log.level=info
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-soevai
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards:ro
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: 'false'
      GF_AUTH_ANONYMOUS_ENABLED: 'false'
      GF_SERVER_ROOT_URL: 'https://${FQDN:-localhost}/grafana/'
      GF_SERVER_SERVE_FROM_SUB_PATH: 'true'
      GF_SECURITY_ALLOW_EMBEDDING: 'true'
      GF_SECURITY_COOKIE_SAMESITE: 'lax'
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter-soevai
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  metrics:
    image: ghcr.io/virtuos/librechat_exporter:main
    container_name: librechat-metrics
    restart: always
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/
      MONGODB_DATABASE: LibreChat
      LOGGING_LEVEL: info
      METRICS_CACHE_ENABLED: "true"
      METRICS_CACHE_TTL: "60"
      ENABLE_BASIC_METRICS: "true"
      ENABLE_TOKEN_METRICS: "true"
      ENABLE_USER_METRICS: "true"
      ENABLE_MODEL_METRICS: "true"
      ENABLE_TIME_WINDOW_METRICS: "true"
      ENABLE_RATING_METRICS: "true"
      ENABLE_TOOL_METRICS: "true"
      ENABLE_FILE_METRICS: "true"

volumes:
  pgdata2:
  prometheus_data:
  alertmanager_data:
  grafana_data:
