services:
  api:
    # Update the image name to match your GitHub Container Registry
    # Format: ghcr.io/<your-github-username>/kwink-soevai-api:latest
    image: ${LIBRECHAT_IMAGE:-ghcr.io/gradient-ds/kwink-soevai-api:latest}
    container_name: librechat_api
    ports:
      - 3080:3080
    depends_on:
      - mongodb
      - rag_api
    restart: always
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
      SOEVAI_ROOT: /app
      ADMIN_OVERLAY_PATH: /app/admin-overrides.yaml
      CONFIG_PATH: /app/librechat.soev.ai.yaml
      BASE_CONFIG_PATH: /app/soev.ai.yaml
      HOST: 0.0.0.0
      PORT: 3080
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      CREDS_KEY: ${CREDS_KEY}
      CREDS_IV: ${CREDS_IV}
      MONGO_URI: mongodb://mongodb:27017/LibreChat
      MEILI_HOST: http://meilisearch:7700
      RAG_PORT: ${RAG_PORT:-8000}
      RAG_API_URL: http://rag_api:${RAG_PORT:-8000}
      DOMAIN_CLIENT: ${DOMAIN_CLIENT:-https://gradient-testing.nl}
      DOMAIN_SERVER: ${DOMAIN_SERVER:-https://gradient-testing.nl}
      TRUST_PROXY: "1"
      TRUST_REVERSE_PROXY: true
      APP_TITLE: ${APP_TITLE:-kwink.soev.ai}
      
      # Web Search Configuration (External VM)
      # Set these in .env file with the IP/hostname of the scraper VM
      SEARXNG_INSTANCE_URL: ${SEARXNG_INSTANCE_URL:-http://10.0.0.2:8080}
      FIRECRAWL_API_URL: ${FIRECRAWL_API_URL:-http://10.0.0.2:3002}
      FIRECRAWL_API_KEY: ${FIRECRAWL_API_KEY:-default-local-key}
      JINA_API_URL: ${JINA_API_URL:-http://10.0.0.2:8001/v1}
      
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      ALLOW_REGISTRATION: ${ALLOW_REGISTRATION:-false}
      ALLOW_UNVERIFIED_EMAIL_LOGIN: ${ALLOW_UNVERIFIED_EMAIL_LOGIN:-false}
      ALLOW_EMAIL_LOGIN: ${ALLOW_EMAIL_LOGIN:-true}
      CUSTOM_FOOTER: soev.ai - Soevereine AI voor Nederland | Controleer belangrijke informatie, AI kan soms fouten maken.
      CHECK_BALANCE: true
      START_BALANCE: 2000000
      ALLOW_SHARED_LINKS: false
      
      # UbiOps Configuration
      UBIOPS_KEY: ${UBIOPS_KEY}

      ENDPOINTS: ${ENDPOINTS}
    volumes:
      - ./soev.ai.yaml:/app/soev.ai.yaml:ro
      - ./librechat.soev.ai.yaml:/app/librechat.soev.ai.yaml:rw
      - ./admin-overrides.yaml:/app/admin-overrides.yaml:rw
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs

  client:
    image: nginx:1.27.0-alpine
    container_name: nginx-soevai
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    restart: always
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
      - /srv/soevai/certbot-www:/var/www/certbot
      - /srv/soevai/letsencrypt:/etc/letsencrypt
  mongodb:
    container_name: chat-mongodb
    # ports:  # Uncomment this to access mongodb from outside docker, not safe in deployment
    #   - 27018:27017
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    command: ["mongod", "--bind_ip_all", "--noauth"]

  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.12.3
    restart: always
    # ports: # Uncomment this to access meilisearch from outside docker
    #   - 7700:7700 # if exposing these ports, make sure your master key is not the default value
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - ./meili_data_v1.12:/meili_data
  vectordb:
    image: pgvector/pgvector:0.8.0-pg15-trixie
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    volumes:
      - pgdata2:/var/lib/postgresql/data


  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev:latest
    container_name: dev-rag-api
    restart: unless-stopped
    depends_on:
      - vectordb
    environment:
      DB_HOST: vectordb
      RAG_PORT: 8000
      OPENAI_API_KEY: ${UBIOPS_RAG}
      OPENAI_BASE_URL: ${RAG_OPENAI_BASE_URL}
      EMBEDDINGS_MODEL: ${RAG_EMBEDDINGS_MODEL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      RAG_CHECK_EMBEDDING_CTX_LENGTH: false
    env_file:
      - .env

  certbot:
    image: certbot/certbot:latest
    container_name: certbot-soevai
    volumes:
      - /srv/soevai/letsencrypt:/etc/letsencrypt
      - /srv/soevai/certbot-www:/var/www/certbot
      - /srv/soevai/letsencrypt-log:/var/log/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: >-
      /bin/sh -c '
        trap exit TERM;
        while :; do
          certbot renew --quiet --deploy-hook "docker exec nginx-soevai nginx -s reload" || true;
          sleep 12h;
        done'
    depends_on:
      - client
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  pgdata2:
